[env]
TERM = "xterm-256color"
[window]
padding.x = 20
padding.y = 20
[general]
import = [
    "~/.config/alacritty/themes/themes/nackerthemes.toml"
]
#decorations = "Buttonless"
#opacity = 0.92
#blur = true 
[font]
normal.family = "CodeNewRoman Nerd Font Mono"
size = 14.5
